### ISSUE TITLE
Add namespaces to the root element

### ISSUE THREAD

**Issue by z3d0** [mtownsend5512/collection-xml#1]
How can I add namespaces to the root element?
So that it returns something like:

`<CustomRoot xmlns:ds="XXX" xmlns:p="YYY" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" parameter="ZZZ" xsi:schemaLocation="http://someurl/file.xsd">`

At the moment I'm using _str_replace_

Thanks in advance!

**Comment by mtownsend5512** [comment]
$collection->toXml([
		'rootElementName' => 'CustomRoot',
		'_attributes' => [
			'xmlns:ds' => 'XXX',
			'xmlns:p' => 'YYY',
			'xmlns:xsi' => 'http://www.w3.org/2001/XMLSchema-instance',
			'parameter' => 'ZZZ',
			'xsi:schemaLocation' => 'http://someurl/file.xsd',
		]
	]);
